### ISSUE TITLE
Version 0.3.4 not being pushed to Kodi 18

### ISSUE THREAD

**Issue by gittest598** [mintsoft/kodi.plugin.ytchannels#19]
First thanks for keeping ytchannels going. The update 0.3.4 was received on Kodi 19.0 and fixed the delete channel problem, but no updates have been sent from the Kodi repo for 18.9 or 18.6. So I'm not sure if the problem is with the Kodi repo or Github not sending it out. I did try a manual update but it just re-installed 0.3.3: Kodi 18.9 is my main daily driver and ytchannels is one of my most used addons, Like many people I'm not ready to switch to 19 just yet.

**Comment by gittest598** [comment]
Fixed. Thanks again.

**Comment by mintsoft** [comment]
@gittest598 I'm also using 18 at the moment (due to LibreElec) so there's no risk of it being dropped from support quite yet. There's always a bit of a delay for the older version due to the way that Kodi actually handles the updates. Plugins for older versions are basically always merged after the most up to date :: https://github.com/xbmc/repo-plugins/pull/3542#event-4608876746
